((makefile-mode . ((tab-width . 4)))
 (makefile-automake-mode . ((tab-width . 4)))
 (c-mode . ((c-file-style  . "gnu")
            ;;(comment-start . "//")
            ;;(comment-end   . "")
            (indent-tabs-mode . nil))))
